### ISSUE TITLE
Changing "Pastie" profile for Github issues

### ISSUE THREAD

**Issue by coolpixgnu** [NaveenRudra/RTTM#12]
Hi,

I'm trying to use my own profile for Paste.com sites:

I just changed for my own at: scrapper_config/scanner-configuration.properties but appear an error when I execute that.

2019-12-18 13:22:36 ERROR ScrapperTool:90 - Something wrong happened in scrappers
java.lang.RuntimeException: ScannerProfile my-own-profile is not defined
	at org.rts.base.profileregistry.ScrapperProfileRegistry.newScrapProfile(ScrapperProfileRegistry.java:28)
	at org.rts.base.ScrapperImpl.initialize(ScrapperImpl.java:51)
	at org.rts.base.ScrapperImpl.initialize(ScrapperImpl.java:38)
	at org.scraptool.ScrapperTool.initializeScrappers(ScrapperTool.java:40)
	at org.scraptool.ScrapperTool.startScrappers(ScrapperTool.java:80)
	at org.scraptool.ScrapperTool.main(ScrapperTool.java:127)
java.lang.RuntimeException: ScannerProfile coolpixgnu is not defined
	at org.rts.base.profileregistry.ScrapperProfileRegistry.newScrapProfile(ScrapperProfileRegistry.java:28)
	at org.rts.base.ScrapperImpl.initialize(ScrapperImpl.java:51)
	at org.rts.base.ScrapperImpl.initialize(ScrapperImpl.java:38)
	at org.scraptool.ScrapperTool.initializeScrappers(ScrapperTool.java:40)
	at org.scraptool.ScrapperTool.startScrappers(ScrapperTool.java:80)
	at org.scraptool.ScrapperTool.main(ScrapperTool.java:127)

**Comment by NaveenRudra** [comment]
Can you share the config data used for pastie profile..

**Comment by coolpixgnu** [comment]
Hi NaveenRudra ,


Btw, I just change :
scrapper.pastie.profile=
scrapper.pastie.regex= "my-key": "([\\w]*)",

#pastebin.com_commercial sue only
scrapper.pastie.profile=**myprofile**
scrapper.pastie.homeurl=https://scrape.pastebin.com/api_scraping.php?limit=500
scrapper.pastie.searchterms=companyabcd hacked,companyabcd breach
scrapper.pastie.regex= "**my-key**": "([\\w]*)",
scrapper.pastie.downloadurl=https://scrape.pastebin.com/api_scrape_item.php?i={id}
scrapper.pastie.timetosleep=10000
scrapper.pastie.trufflehogregex=false
scrapper.pastie.trufflehogentropy=false

**Comment by NaveenRudra** [comment]
Move the profile name back to Pastie.
Currently, there is no option to choose any random name for profile name.

**Comment by coolpixgnu** [comment]
Hi NaveenRudra 

Al already have a pro pastebin profile.

There is not way to include my profile and my key at the setting? in some way?

Thanks for your kindly response.

Kind regards
