### ISSUE TITLE
"Something wrong happened in scrapers"

### ISSUE THREAD

**Issue by OzAven** [NaveenRudra/RTTM#14]
Hello, 
I followed to instructions for the tool setup.
The last step is to run "/opt/RTTM run command java -jar scraptool/target/scraptool-1.0-SNAPSHOT-standalone.jar -t test -c /home/n0r00ij/RTS/scrapper_config/" from inside the container.
I did so and received a hava error as follows:
root@c23541f35546:/opt/RTTM/RTTM# java -jar scraptool/target/scraptool-1.0-SNAPSHOT-standalone.jar -t test -c /home/n0r00ij/RTS/scrapper_config
Initializing of scrapper has started!!
java.nio.file.NoSuchFileException: /home/n0r00ij/RTS/scrapper_config/scanner-configuration.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at org.rts.base.ScrapperImpl.initialize(ScrapperImpl.java:37)
	at org.scraptool.ScrapperTool.initializeScrappers(ScrapperTool.java:40)
	at org.scraptool.ScrapperTool.startScrappers(ScrapperTool.java:80)
	at org.scraptool.ScrapperTool.main(ScrapperTool.java:127)
2019-12-22 10:27:05 ERROR ScrapperTool:90 - Something wrong happened in scrappers
java.nio.file.NoSuchFileException: /home/n0r00ij/RTS/scrapper_config/consumer.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at org.kafkaparser.base.NotificationConsumerThread.getConfig(NotificationConsumerThread.java:64)
	at org.kafkaparser.base.NotificationConsumerThread.<init>(NotificationConsumerThread.java:51)
	at org.kafkaparser.base.NotificationConsumerGroup.<init>(NotificationConsumerGroup.java:20)
	at org.scraptool.ScrapperTool.startScrappers(ScrapperTool.java:86)
	at org.scraptool.ScrapperTool.main(ScrapperTool.java:127)
java.nio.file.NoSuchFileException: /home/n0r00ij/RTS/scrapper_config/consumer.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at org.kafkaparser.base.NotificationConsumerThread.getConfig(NotificationConsumerThread.java:64)
	at org.kafkaparser.base.NotificationConsumerThread.<init>(NotificationConsumerThread.java:51)
	at org.kafkaparser.base.NotificationConsumerGroup.<init>(NotificationConsumerGroup.java:20)
	at org.scraptool.ScrapperTool.startScrappers(ScrapperTool.java:86)
	at org.scraptool.ScrapperTool.main(ScrapperTool.java:127)

Why is this happening? all previous steps passed successfully.

Thanks

**Comment by NaveenRudra** [comment]
Currently you are in root@c23541f35546:/opt/RTTM/RTTM#

Change directory to /opt/RTTM it should work fine.

**Comment by OzAven** [comment]
Worked fine, thanks.
